# Site settings
name: Q10Viking
email: 1193094618@qq.com
author: 黄壮壮
url: http://q10viking.com
#resume_site: http://www.hifreud.com/Resume.io/
github: https://github.com/q10viking/
baseurl: ""
description: Actually, less is more!
meta_description: 黄壮壮;个人博客;学而不思则罔;思而不学则殆;生命不止;折腾不休
motto: It's our wits that make us men.
banner: 非淡泊无以明志，非宁静无以致远
color: 6C7A89
#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
gem: [jekyll-paginate]
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: 
highlighter: Pygments

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae